// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_iiJGISzWnR3ciPyJ42hLwFxOHr902f0',
    appId: '1:834444430066:android:b1f211c632423df35ede6b',
    messagingSenderId: '834444430066',
    projectId: 'healthmanage-d1145',
    storageBucket: 'healthmanage-d1145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB7LTc4fvR74yO2jOX5BiL2lyvNQKMJqU',
    appId: '1:834444430066:ios:9bc2ef1f633d5c7f5ede6b',
    messagingSenderId: '834444430066',
    projectId: 'healthmanage-d1145',
    storageBucket: 'healthmanage-d1145.firebasestorage.app',
    iosBundleId: 'com.example.healthManagementApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-pg5VxPgtAW9FfvyvozY1mSeuAAVbnU8',
    appId: '1:834444430066:web:99bf5b8099ba3fb15ede6b',
    messagingSenderId: '834444430066',
    projectId: 'healthmanage-d1145',
    authDomain: 'healthmanage-d1145.firebaseapp.com',
    storageBucket: 'healthmanage-d1145.firebasestorage.app',
    measurementId: 'G-Z6FX469YC2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-pg5VxPgtAW9FfvyvozY1mSeuAAVbnU8',
    appId: '1:834444430066:web:e8fbe50880a787395ede6b',
    messagingSenderId: '834444430066',
    projectId: 'healthmanage-d1145',
    authDomain: 'healthmanage-d1145.firebaseapp.com',
    storageBucket: 'healthmanage-d1145.firebasestorage.app',
    measurementId: 'G-ELLKZYE6X5',
  );

}